apiVersion: latest
enabled: true
name: gradient-ai/serge
image: ghcr.io/gradient-ai/serge:latest
port: 8008
healthChecks:
  readiness:
    path: /
resources:
  replicas: 1
  instanceType: A6000
  autoscaling:
    enabled: true
    maxReplicas: 2
    metrics:
      - metric: requestDuration
        summary: average
        value: 1.15
      - metric: cpu
        summary: average
        value: 45
      - metric: memory
        summary: average
        value: 45
